/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Talisca;

import Talisca.model.TaliscaEngine;
import javafx.application.Application;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {

    private TaliscaInit taliscaInit;

    @Override
    public void start(Stage primaryStage) throws Exception{
        taliscaInit = new TaliscaInit(new TaliscaEngine(), primaryStage);
        taliscaInit.run();
    }

    @Override
    public void stop() throws IOException {
    }

    public static void main(String[] args) {
        launch(args);
    }
}
